name: Java CI
on: push
jobs:
  Clone-down:  
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: download
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: checkout
        uses: actions/checkout@v2
      - run: ci/build-app.sh

  Test:
    needs: Clone-down
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Test
        uses: actions/checkout@v2
      - run: ci/unit-test-app.sh
     

  Build:
    runs-on: ubuntu-latest
    needs: Clone-down
    steps:
      - name: upload Repo
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .